apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: samwise
spec:
  selector:
    matchLabels:
      app: samwise
  replicas: 1
  template:
    metadata:
      labels:
        app: samwise

    spec:
      serviceAccountName: samwise
      containers:
        - name: samwise
          image: inflatibleyoshi/discord-samwise
          ports:
            - containerPort: 443
          env:
            - name: REDIS_HOST
              value: ""
            - name: VAULT_ROLE_ID
              value: ""
            - name: VAULT_URL
              value: ""