apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: samwise
spec:
  selector:
    matchLabels:
      app: samwise
  replicas: 1
  template:
    metadata:
      labels:
        app: samwise
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/vault-addr: "https://vault:8200"
        vault.hashicorp.com/vault-tls-secret: "vault-tls"
        vault.hashicorp.com/role: 'samwise'

    spec:
      serviceAccountName: samwise
      containers:
        - name: samwise
          image: inflatibleyoshi/discord-samwise
          ports:
            - containerPort: 443
          env:
            - name: BOT_TOKEN
              value: "vault:secret/data/samwise#BOT_TOKEN"
            - name: REDIS_PASSWORD
              value: "vault:secret/data/redis#PASSWORD"