apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: samwise
spec:
  selector:
    matchLabels:
      app: samwise
  replicas: 1
  template:
    metadata:
      labels:
        app: samwise

    spec:
      serviceAccountName: default
      containers:
        - name: samwise
          image: discord-samwise
          imagePullPolicy: Never
          ports:
            - containerPort: 443
          env:
            - name: REDIS_HOST
              value: "10.101.77.31"
            - name: VAULT_URL
              value: "http://10.108.156.3:8200/"
            - name: VAULT_TOKEN
              value: "s.um5VS2Npg6G9xyPHGsJaFK5p"
            - name: VAULT_CA
              valueFrom:
                secretKeyRef:
                  name: "samwise-vault-ca"
                  key: "vault.ca"
