apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: samwise
spec:
  selector:
    matchLabels:
      app: samwise
  replicas: 1
  template:
    metadata:
      labels:
        app: samwise

    spec:
      hostAliases:
      - ip: "10.152.183.49"
        hostnames:
        - "vault-server-tls.vault.svc"
        - "vault-server-tls.vault.svc.cluster.local"
      serviceAccountName: default
      containers:
        - name: samwise
          image: inflatibleyoshi/discord-samwise:public
          imagePullPolicy: Always
          ports:
            - containerPort: 443
          env:
            - name: REDIS_HOST
              value: "10.152.183.119"
            - name: VAULT_URL
              value: "https://vault-server-tls.vault.svc:8200/"
            - name: VAULT_TOKEN
              value: "s.lEdoY0TBirrW80LHAK4MMhAG"
            - name: VAULT_CA
              valueFrom:
                secretKeyRef:
                  name: "samwise-vault-ca"
                  key: "vault.ca"
