apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: samwise
spec:
  selector:
    matchLabels:
      app: samwise
  replicas: 1
  template:
    metadata:
      labels:
        app: samwise
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "web"
        vault.hashicorp.com/agent-inject-secret-config: "secret/data/web"
        # Environment variable export template
        vault.hashicorp.com/agent-inject-template-config: |
          {{ with secret "secret/data/web" -}}
            export api_key="{{ .Data.data.payments_api_key }}"
          {{- end }}
    spec:
      containers:
        - name: samwise
          image: inflatibleyoshi/discord-samwise
          args: [ "sh", "-c", "source /vault/secrets/config && <entrypoint script>" ]
          ports:
            - containerPort: 443